### ISSUE TITLE
This repository is a Mess.

### ISSUE THREAD

**Issue by e-beach** [teslaworksumn/guild-master#1]
We need to divide this repo into a bunch of smaller ones and get rid of legacy code.

**Comment by e-beach** [comment]
@hkethi002 Harsha would you care to delete any of the old broken stuff? It'd take me a long time to dig through.

Keep in mind we can always grab old stuff from the git history even after its deleted.

**Comment by hkethi002** [comment]
Sure thing, I'll get it done tonight.

**Comment by hkethi002** [comment]
So I've purged the repo, and I have stored the directories locally to move them to a new repository such as JoyStickControls.

**Comment by e-beach** [comment]
@computergeek125 Ryan, can you create 5 blank repos with dummy names like guild_1, guild_2, ... guild5 for us to push code to? Thanks a lot.

**Comment by computergeek125** [comment]
Should be done with @teslaworksumn/guild-of-robotic-artisans as admin.  If one of the permissions did not save, let me know.

[teslaworksumn/guild-1](github.com/teslaworksumn/guild-1)
[teslaworksumn/guild-2](github.com/teslaworksumn/guild-2)
[teslaworksumn/guild-3](github.com/teslaworksumn/guild-3)
[teslaworksumn/guild-4](github.com/teslaworksumn/guild-4)
[teslaworksumn/guild-5](github.com/teslaworksumn/guild-5)

**Comment by hkethi002** [comment]
So as far as how we should divide up the code into repos, I was thinking one for Teleoperated, one for arduino code for the automated, and one for changing an image through Python and MATLAB. What are your thoughts @e-beach ?

**Comment by e-beach** [comment]
@hkethi002 Sounds good to me.

**Comment by e-beach** [comment]
@hkethi002 were you thinking the MATLAB code that Michael showed us on Sunday would go in this repo?

**Comment by hkethi002** [comment]
I was thinking we should probably rename all the repos

**Comment by e-beach** [comment]
@hkethi002 ??

I was thinking that this repo contains the code image => gcode, and MATLAB code from Sunday also works toward that purpose, so we can put them in the same repo. I don't see how repo names really affect that, but yes we should rename them.

**Comment by hkethi002** [comment]
Yeah, that's kinda what I was getting at in the previous 2 messages.

**Comment by e-beach** [comment]
@hkethi002 Do you know what the Droid directories are for? I'm confused because they are empty.

**Comment by e-beach** [comment]
Fixed by  e820a5b
