### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by elliott-beach** [teslaworksumn/guild-master#2]
For python code,
how would we feel about following pep8 style and using this linter?
https://pypi.python.org/pypi/pep8

**Comment by hkethi002** [comment]
Good idea, I can start converting the code we have now to follow these style guidelines.

**Comment by e-beach** [comment]
@hkethi002 Is the atom package for pylint working for you? It works for me.

**Comment by e-beach** [comment]
@hkethi002 @MOLLYBAS I'm reorganizing all the files, just getting rid of subdirectories where they aren't needed. Also, Harsha, do you know which version is the version we are interested in Arduino/stepper_motor_serial_ctrl/ ?

**Comment by hkethi002** [comment]
I'm not exactly sure, that is what is going to be replaced with Marlin by Michael.

**Comment by michaelr123** [comment]
I'm not sure what you mean by this, maybe if i post a description of what the system is doing it will help? 

marlin will allow a gcode sender (repetier, pronterface, etc) to communicate with the arduino (with marlin on it, which is a huge arduino sketch). Once this communication line is open, the Gcode sender reads through the Gcode file and sends it, line by line to the arduino. The arduino, running marlin, interprets this code and then figures out what to do with the motors, it then sends pulses to the stepper drivers (the little boards on top of the red board on top of the arduino) which then translates the pulses to energize the coils in the stepper motors to do whatever they need to do to move to the position commanded by the Gcode. 

All we're doing is creating the Gcode itself. So you guys don't need to worry about the Gcode sender, the motion planner, how the motors are accelerating or anything down the line in the system. Pronterface and marlin will take care of everything for you guys. 

We'll make a few small changes to the configuration header file in marlin to adapt it to our system and that's it. 

let me know if this is helpful or if I don't understand what you guys are talking about?

**Comment by hkethi002** [comment]
So we don't need to write any arduino code?

**Comment by michaelr123** [comment]
Nope, don't worry about it, marlin will take care of everything. I'll take care of configuring the system.

**Comment by e-beach** [comment]
@hkethi002 Were you using python3 for this project? I assumed it was python2, just checking.

**Comment by e-beach** [comment]
I guess we're using python2 because I don't like putting parentheses around print(statements). Sorry Harsha.

**Comment by computergeek125** [comment]
Just as a point of information: stuff like that is the REASON that python 2 still lives.  I highly recommend python 3.  Only use py 2 if a library you need requires it (like PyGame)

**Comment by hkethi002** [comment]
Since we don't need any libraries that are only on python 2 and I agree with Ryan, we should use python 3. Most of the code such as the IP1 and gcoder and interpolater was written with python 3 in mind.
