### ISSUE TITLE
Team Heirarchy

### ISSUE THREAD

**Issue by e-beach** [teslaworksumn/guild-master#3]
@computergeek125 
Can you add @MOLLYBAS, @michaelr123, @aswege
to the @teslaworksumn/guild-of-robotic-artisans team?
Also, is there a reason @hkethi002 and myself do not have the authority to add new people? Or am I mistaken and we actually do?

**Comment by computergeek125** [comment]
I think I'd have to grant admin access to the org to modify the team.  Everyone's added now though

**Comment by e-beach** [comment]
@computergeek125 
It looks like MOLLYBAS and michaelr123 are still not in @teslaworksumn/guild-of-robotic-artisans? Am I mistaken?

**Comment by computergeek125** [comment]
They have yet to accept their invitations

**Comment by MOLLYBAS** [comment]
How do I accept?

**Comment by computergeek125** [comment]
You should have received an email
