### ISSUE TITLE
PTG Files

### ISSUE THREAD

**Issue by e-beach** [teslaworksumn/guild-master#4]
@hkethi002 How do we generate the ptg files from the jpg files? My memory fails me.

**Comment by e-beach** [comment]
I'm also very confused by IP1.py

**Comment by e-beach** [comment]
The file `IP1.py` is buggy, depending on the encoding of the image file.
If you have imageMagick utilties, you can use the `identify` command to examine image files.
This file needs documentation for what kind of files it can convert, and also needs to be shifted to pep8 style.

**Comment by e-beach** [comment]
@hkethi002 Just curious, do you know why the ptg files were deleted? My thought is they are useful for testing.

**Comment by e-beach** [comment]
@hkethi002 Do you know the justification behind the ratioFile? What is that file for?

**Comment by hkethi002** [comment]
It was just the easiest way to store information needed by the GCoder from the image processor. But now that the entire process is in python there is probably a better way.

**Comment by e-beach** [comment]
@hkethi002  What is the meaning of the information, i.e. why is the number 8.0 hardcoded?

**Comment by e-beach** [comment]
See https://github.com/teslaworksumn/guild-master/wiki/Canvas-Width-and-Resolution
