### ISSUE TITLE
pathPlanners/main.py argument parsing

### ISSUE THREAD

**Issue by elliott-beach** [teslaworksumn/guild-master#5]
Something is wrong with the argument parsing in this file.
Specifically, the argument input file, passed with the arcane `-ci` input parameter, only works in the style `-ci_<filename>`, requiring the underscore rather than the space, which is basically incorrect.
It would be better to use python's getopt library, or something like it.

**Comment by hkethi002** [comment]
Ok, I'm not familiar with that library but I will look into it.

**Comment by e-beach** [comment]
I think this is something Amalia might be interested in helping with ( oddly, she still hasn't been added to the team. I messaged computergeek125 about that).

**Comment by computergeek125** [comment]
See also: doctopt and argparse.  I think @bookdude13 uses docopt with the lightshow things.

**Comment by e-beach** [comment]
Also, I might change IP1.py to take in the arguments as a filename. I think this will make automation easier.

**Comment by bookdude13** [comment]
Can confirm that docopt is great for dealing with command line arguments in python
