### ISSUE TITLE
Bug in GCoder.py

### ISSUE THREAD

**Issue by elliott-beach** [teslaworksumn/guild-master#6]
I think there is a bug in the GCoder.py file.

https://github.com/teslaworksumn/guild-master/blob/82507c1ed6899922071c3aca0bb15ed68d299cb5/GCoder.py#L61

This line will never be executed, so the brush will never be removed from a state of lifted.
@hkethi002 Do you know if this would make a difference in the code based on your experience?

**Comment by e-beach** [comment]
2016's code was broken in several ways, and this may be one of htem
