### ISSUE TITLE
DinverseRobotic Parameters

### ISSUE THREAD

**Issue by elliott-beach** [teslaworksumn/guild-master#7]
@michaelr123 Would you care to document what each of the parameters to the function [DInverseRobotic ](https://github.com/teslaworksumn/guild-master/blob/82507c1ed6899922071c3aca0bb15ed68d299cb5/inverse-kinematics/InverseKinematicSolver.m#L19) mean? Its hard to understand otherwise. Thanks 😃

**Comment by michaelr123** [comment]
i can do that today
